- lasttime 0.5.8 fix (always run bootstrap before tagging release)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_VERSION='0.5.8'
 PACKAGE_STRING='kydpdict 0.5.8'
 PACKAGE_BUGREPORT='ytm@friko.onet.pl'
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP CXX CXXFLAGS ac_ct_CXX CXXCPP SET_MAKE LUPDATE LRELEASE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP CXX CXXFLAGS ac_ct_CXX CXXCPP SET_MAKE QT_INCLUDES QT_LDFLAGS MOC UIC QT_LIB QT_VERSION LUPDATE LRELEASE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -821,6 +821,13 @@ if test -n "$ac_init_help"; then
      short | recursive ) echo "Configuration of kydpdict 0.5.8:";;
    esac
   cat <<\_ACEOF
+
+Optional Packages:
+  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
+  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-qt-dir           where the root of Qt is installed
+  --with-qt-includes      where the Qt includes are.
+  --with-qt-libraries     where the Qt library is installed.
 
 Some influential environment variables:
   CC          C compiler command
@@ -3601,7 +3608,366 @@ echo "${ECHO_T}no" >&6
 fi
 
 
-QT_DO_IT_ALL
+
+
+			FATAL=1
+
+
+# Check whether --with-qt-dir or --without-qt-dir was given.
+if test "${with_qt_dir+set}" = set; then
+  withval="$with_qt_dir"
+   qt_cv_dir=`eval echo "$withval"`
+fi;
+
+
+# Check whether --with-qt-includes or --without-qt-includes was given.
+if test "${with_qt_includes+set}" = set; then
+  withval="$with_qt_includes"
+   qt_cv_includes=`eval echo "$withval"`
+fi;
+
+
+# Check whether --with-qt-libraries or --without-qt-libraries was given.
+if test "${with_qt_libraries+set}" = set; then
+  withval="$with_qt_libraries"
+    qt_cv_libraries=`eval echo "$withval"`
+fi;
+
+		if test -z "$qt_cv_dir"; then
+		qt_cv_dir=$QTDIR
+	fi
+
+		if test -n "$qt_cv_dir"; then
+		if test -z "$qt_cv_includes"; then
+			qt_cv_includes=$qt_cv_dir/include
+		fi
+		if test -z "$qt_cv_libraries"; then
+			qt_cv_libraries=$qt_cv_dir/lib
+		fi
+	fi
+
+		QT_INCLUDES=
+	QT_LDFLAGS=
+	if test -n "$qt_cv_includes"; then
+		QT_INCLUDES="-I$qt_cv_includes"
+	fi
+	if test -n "$qt_cv_libraries"; then
+		QT_LDFLAGS="-L$qt_cv_libraries"
+	fi
+
+
+
+
+
+	echo "$as_me:$LINENO: checking for moc2" >&5
+echo $ECHO_N "checking for moc2... $ECHO_C" >&6
+	if test "${qt_cv_path_moc2+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+		qt_cv_path_moc2="NONE"
+		if test -n "$ac_moc2"; then
+			qt_cv_path_moc2="$ac_moc2";
+		else
+			dirs="$qt_cv_dir/bin"
+			qt_save_IFS=$IFS
+			IFS=':'
+			for dir in $PATH; do
+				dirs="$dirs $dir"
+			done
+			IFS=$qt_save_IFS
+
+			for dir in $dirs; do
+				if test -x "$dir/moc2"; then
+					if test -n ""; then
+						evalstr="$dir/moc2  2>&1 "
+						if eval $evalstr; then
+							qt_cv_path_moc2="$dir/moc2"
+							break
+						fi
+					else
+						qt_cv_path_moc2="$dir/moc2"
+						break
+					fi
+				fi
+			done
+		fi
+
+fi
+
+
+	if test -z "$qt_cv_path_moc2" || test "$qt_cv_path_moc2" = "NONE"; then
+		echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+
+	else
+		echo "$as_me:$LINENO: result: $qt_cv_path_moc2" >&5
+echo "${ECHO_T}$qt_cv_path_moc2" >&6
+		ac_moc2=$qt_cv_path_moc2
+	fi
+
+
+	echo "$as_me:$LINENO: checking for moc" >&5
+echo $ECHO_N "checking for moc... $ECHO_C" >&6
+	if test "${qt_cv_path_moc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+		qt_cv_path_moc="NONE"
+		if test -n "$ac_moc1"; then
+			qt_cv_path_moc="$ac_moc1";
+		else
+			dirs="$qt_cv_dir/bin"
+			qt_save_IFS=$IFS
+			IFS=':'
+			for dir in $PATH; do
+				dirs="$dirs $dir"
+			done
+			IFS=$qt_save_IFS
+
+			for dir in $dirs; do
+				if test -x "$dir/moc"; then
+					if test -n ""; then
+						evalstr="$dir/moc  2>&1 "
+						if eval $evalstr; then
+							qt_cv_path_moc="$dir/moc"
+							break
+						fi
+					else
+						qt_cv_path_moc="$dir/moc"
+						break
+					fi
+				fi
+			done
+		fi
+
+fi
+
+
+	if test -z "$qt_cv_path_moc" || test "$qt_cv_path_moc" = "NONE"; then
+		echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+
+	else
+		echo "$as_me:$LINENO: result: $qt_cv_path_moc" >&5
+echo "${ECHO_T}$qt_cv_path_moc" >&6
+		ac_moc1=$qt_cv_path_moc
+	fi
+
+
+	if test -n "$ac_moc1" -a -n "$ac_moc2"; then
+				$ac_moc1 -v 2>&1 | grep "Qt 3" >/dev/null
+		if test "$?" = 0; then
+			ac_moc=$ac_moc1;
+		else
+			ac_moc=$ac_moc2;
+		fi
+	else
+		if test -n "$ac_moc1"; then
+			ac_moc=$ac_moc1;
+		else
+			ac_moc=$ac_moc2;
+		fi
+	fi
+
+	if test -z "$ac_moc"  -a "$FATAL" = 1; then
+		{ { echo "$as_me:$LINENO: error: moc binary not found in \$PATH or $qt_cv_dir/bin !" >&5
+echo "$as_me: error: moc binary not found in \$PATH or $qt_cv_dir/bin !" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+
+	MOC=$ac_moc
+
+
+
+	echo "$as_me:$LINENO: checking for uic" >&5
+echo $ECHO_N "checking for uic... $ECHO_C" >&6
+	if test "${qt_cv_path_uic+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+		qt_cv_path_uic="NONE"
+		if test -n "$ac_uic"; then
+			qt_cv_path_uic="$ac_uic";
+		else
+			dirs="$qt_cv_dir/bin"
+			qt_save_IFS=$IFS
+			IFS=':'
+			for dir in $PATH; do
+				dirs="$dirs $dir"
+			done
+			IFS=$qt_save_IFS
+
+			for dir in $dirs; do
+				if test -x "$dir/uic"; then
+					if test -n ""; then
+						evalstr="$dir/uic  2>&1 "
+						if eval $evalstr; then
+							qt_cv_path_uic="$dir/uic"
+							break
+						fi
+					else
+						qt_cv_path_uic="$dir/uic"
+						break
+					fi
+				fi
+			done
+		fi
+
+fi
+
+
+	if test -z "$qt_cv_path_uic" || test "$qt_cv_path_uic" = "NONE"; then
+		echo "$as_me:$LINENO: result: not found" >&5
+echo "${ECHO_T}not found" >&6
+
+	else
+		echo "$as_me:$LINENO: result: $qt_cv_path_uic" >&5
+echo "${ECHO_T}$qt_cv_path_uic" >&6
+		ac_uic=$qt_cv_path_uic
+	fi
+
+	if test -z "$ac_uic" -a "$FATAL" = 1; then
+		{ { echo "$as_me:$LINENO: error: uic binary not found in \$PATH or $qt_cv_dir/bin !" >&5
+echo "$as_me: error: uic binary not found in \$PATH or $qt_cv_dir/bin !" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+
+	UIC=$ac_uic
+
+
+
+	echo "$as_me:$LINENO: checking for Qt library name" >&5
+echo $ECHO_N "checking for Qt library name... $ECHO_C" >&6
+
+	if test "${qt_cv_libname+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+		ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+		SAVE_CXXFLAGS=$CXXFLAGS
+		CXXFLAGS="$CXXFLAGS $QT_INCLUDES $QT_LDFLAGS"
+
+		for libname in -lqt3 -lqt2 -lqt -lqt-mt;
+		do
+
+	SAVE_LIBS="$LIBS"
+	LIBS="$LIBS $libname"
+	cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+	#include <qglobal.h>
+	#include <qstring.h>
+
+int
+main ()
+{
+
+	QString s("mangle_failure");
+	#if (QT_VERSION < 221)
+	break_me_(\\\);
+	#endif
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  qt_cv_libname=$libname
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+	LIBS="$SAVE_LIBS"
+
+			if test -n "$qt_cv_libname"; then
+				break;
+			fi
+		done
+
+		CXXFLAGS=$SAVE_CXXFLAGS
+
+fi
+
+
+	if test -z "$qt_cv_libname"; then
+		echo "$as_me:$LINENO: result: failed" >&5
+echo "${ECHO_T}failed" >&6
+		if test "$FATAL" = 1 ; then
+			{ { echo "$as_me:$LINENO: error: Cannot compile a simple Qt executable. Check you have the right \$QTDIR !" >&5
+echo "$as_me: error: Cannot compile a simple Qt executable. Check you have the right \$QTDIR !" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+	else
+		echo "$as_me:$LINENO: result: $qt_cv_libname" >&5
+echo "${ECHO_T}$qt_cv_libname" >&6
+	fi
+
+
+	QT_LIB=$qt_cv_libname;
+
+
+	if test -n "$qt_cv_libname"; then
+
+	echo "$as_me:$LINENO: checking Qt version" >&5
+echo $ECHO_N "checking Qt version... $ECHO_C" >&6
+if test "${lyx_cv_qtversion+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+		ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+		SAVE_CPPFLAGS=$CPPFLAGS
+		CPPFLAGS="$CPPFLAGS $QT_INCLUDES"
+
+		cat > conftest.$ac_ext <<EOF
+#line 3951 "configure"
+#include "confdefs.h"
+#include <qglobal.h>
+"%%%"QT_VERSION_STR"%%%"
+EOF
+		lyx_cv_qtversion=`(eval "$ac_cpp conftest.$ac_ext") 2>&5 | \
+			grep '^"%%%"'  2>/dev/null | \
+			sed -e 's/"%%%"//g' -e 's/"//g'`
+		rm -f conftest.$ac_ext
+		CPPFLAGS=$SAVE_CPPFLAGS
+
+fi
+echo "$as_me:$LINENO: result: $lyx_cv_qtversion" >&5
+echo "${ECHO_T}$lyx_cv_qtversion" >&6
+
+	QT_VERSION=$lyx_cv_qtversion
+
+
+	fi
+
 
 if test x"$qt_cv_libraries" = "x"; then
     { { echo "$as_me:$LINENO: error: you have to provide both --with-qt-includes and --with-qt-libraries" >&5
@@ -4468,6 +4834,12 @@ s,@CXXFLAGS@,$CXXFLAGS,;t t
 s,@ac_ct_CXX@,$ac_ct_CXX,;t t
 s,@CXXCPP@,$CXXCPP,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
+s,@QT_INCLUDES@,$QT_INCLUDES,;t t
+s,@QT_LDFLAGS@,$QT_LDFLAGS,;t t
+s,@MOC@,$MOC,;t t
+s,@UIC@,$UIC,;t t
+s,@QT_LIB@,$QT_LIB,;t t
+s,@QT_VERSION@,$QT_VERSION,;t t
 s,@LUPDATE@,$LUPDATE,;t t
 s,@LRELEASE@,$LRELEASE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
