- poprawki autoconfa - wymagane Qt >=3.1; podwójny // w ścieżce z $QTDIR,   $QTDIR nie brany pod uwagę przy szukaniu lupdate i lrelease

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3616,7 +3616,7 @@ fi
 # Check whether --with-qt-dir or --without-qt-dir was given.
 if test "${with_qt_dir+set}" = set; then
   withval="$with_qt_dir"
-   qt_cv_dir=`eval echo "$withval"/`
+   qt_cv_dir=`eval echo "$withval"`
 fi;
 
 
@@ -3975,9 +3975,13 @@ echo "$as_me: error: you have to provide both --with-qt-includes and --with-qt-l
    { (exit 1); exit 1; }; }
 fi
 
+if test -n "$qt_cv_dir"; then
+    QTDIR=$qt_cv_dir
+fi
+
 # Required Qt version
 QTMAJOR=3
-QTMIDDLE=0
+QTMIDDLE=1
 QTMINOR=0
 
 aIFS=$IFS
@@ -4007,8 +4011,8 @@ done
 IFS=$aIFS
 
 if test 0$FAULT -eq 1; then
-    { { echo "$as_me:$LINENO: error: found Qt $QT_VERSION, Qt >= $QTMAJOR.$QTMIDDLE.$QTMINOR required" >&5
-echo "$as_me: error: found Qt $QT_VERSION, Qt >= $QTMAJOR.$QTMIDDLE.$QTMINOR required" >&2;}
+    { { echo "$as_me:$LINENO: error: found Qt $QT_VERSION, Qt >= $QTMAJOR.$QTMIDDLE required" >&5
+echo "$as_me: error: found Qt $QT_VERSION, Qt >= $QTMAJOR.$QTMIDDLE required" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -4068,7 +4072,7 @@ else
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-as_dummy="$PATH:/usr/X11R6/bin:/usr/bin:/usr/local/bin:/usr/local/qt/bin"
+as_dummy="$PATH:$QTDIR/bin:/usr/X11R6/bin:/usr/bin:/usr/local/bin:/usr/local/qt/bin"
 for as_dir in $as_dummy
 do
   IFS=$as_save_IFS
@@ -4153,7 +4157,7 @@ else
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-as_dummy="$PATH:/usr/X11R6/bin:/usr/bin:/usr/local/bin:/usr/local/qt/bin"
+as_dummy="$PATH:$QTDIR/bin:/usr/X11R6/bin:/usr/bin:/usr/local/bin:/usr/local/qt/bin"
 for as_dir in $as_dummy
 do
   IFS=$as_save_IFS
